Fix local building of roxie container image
Without this fix, locally invoking `make docker-build` fails due to

```
[...]
[1/2] STEP 11/15: RUN echo "Building for ${TARGETOS}/${TARGETARCH}" &&     CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build     -ldflags "-w -s -X main.version=${VERSION} -X main.gitCommit=${GIT_COMMIT} -X main.buildDate=${BUILD_DATE}"     -o roxie     ./cmd
Building for linux/arm64
github.com/stackrox/roxie/cmd: go build github.com/stackrox/roxie/cmd: copying /tmp/go-build3080175455/b001/exe/a.out: open roxie: permission denied
Error: building at STEP "RUN echo "Building for ${TARGETOS}/${TARGETARCH}" &&     CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build     -ldflags "-w -s -X main.version=${VERSION} -X main.gitCommit=${GIT_COMMIT} -X main.buildDate=${BUILD_DATE}"     -o roxie     ./cmd": while running runtime: exit status 1

make: *** [Makefile:190: docker-build] Error 1
```